version: '3'

services:
  app:
    container_name: docker-news-mongo
    restart: always
    build: .
    ports:
      - '83:4000'
    links:
      - mongo
  mongo: 
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'   
     
